# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='anything', upload_to='articles'),
        ),
    ]
